// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"xcimoc-data-server/models"
)

func newSyncEvent(db *gorm.DB, opts ...gen.DOOption) syncEvent {
	_syncEvent := syncEvent{}

	_syncEvent.syncEventDo.UseDB(db, opts...)
	_syncEvent.syncEventDo.UseModel(&models.SyncEvent{})

	tableName := _syncEvent.syncEventDo.TableName()
	_syncEvent.ALL = field.NewAsterisk(tableName)
	_syncEvent.ID = field.NewUint(tableName, "id")
	_syncEvent.UserID = field.NewUint(tableName, "user_id")
	_syncEvent.Type = field.NewString(tableName, "type")
	_syncEvent.Payload = field.NewString(tableName, "payload")
	_syncEvent.PayloadHash = field.NewString(tableName, "payload_hash")
	_syncEvent.ClientID = field.NewString(tableName, "client_id")
	_syncEvent.CreatedAt = field.NewTime(tableName, "created_at")

	_syncEvent.fillFieldMap()

	return _syncEvent
}

type syncEvent struct {
	syncEventDo

	ALL         field.Asterisk
	ID          field.Uint
	UserID      field.Uint
	Type        field.String
	Payload     field.String
	PayloadHash field.String
	ClientID    field.String
	CreatedAt   field.Time

	fieldMap map[string]field.Expr
}

func (s syncEvent) Table(newTableName string) *syncEvent {
	s.syncEventDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s syncEvent) As(alias string) *syncEvent {
	s.syncEventDo.DO = *(s.syncEventDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *syncEvent) updateTableName(table string) *syncEvent {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewUint(table, "id")
	s.UserID = field.NewUint(table, "user_id")
	s.Type = field.NewString(table, "type")
	s.Payload = field.NewString(table, "payload")
	s.PayloadHash = field.NewString(table, "payload_hash")
	s.ClientID = field.NewString(table, "client_id")
	s.CreatedAt = field.NewTime(table, "created_at")

	s.fillFieldMap()

	return s
}

func (s *syncEvent) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *syncEvent) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 7)
	s.fieldMap["id"] = s.ID
	s.fieldMap["user_id"] = s.UserID
	s.fieldMap["type"] = s.Type
	s.fieldMap["payload"] = s.Payload
	s.fieldMap["payload_hash"] = s.PayloadHash
	s.fieldMap["client_id"] = s.ClientID
	s.fieldMap["created_at"] = s.CreatedAt
}

func (s syncEvent) clone(db *gorm.DB) syncEvent {
	s.syncEventDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s syncEvent) replaceDB(db *gorm.DB) syncEvent {
	s.syncEventDo.ReplaceDB(db)
	return s
}

type syncEventDo struct{ gen.DO }

func (s syncEventDo) Debug() *syncEventDo {
	return s.withDO(s.DO.Debug())
}

func (s syncEventDo) WithContext(ctx context.Context) *syncEventDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s syncEventDo) ReadDB() *syncEventDo {
	return s.Clauses(dbresolver.Read)
}

func (s syncEventDo) WriteDB() *syncEventDo {
	return s.Clauses(dbresolver.Write)
}

func (s syncEventDo) Session(config *gorm.Session) *syncEventDo {
	return s.withDO(s.DO.Session(config))
}

func (s syncEventDo) Clauses(conds ...clause.Expression) *syncEventDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s syncEventDo) Returning(value interface{}, columns ...string) *syncEventDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s syncEventDo) Not(conds ...gen.Condition) *syncEventDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s syncEventDo) Or(conds ...gen.Condition) *syncEventDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s syncEventDo) Select(conds ...field.Expr) *syncEventDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s syncEventDo) Where(conds ...gen.Condition) *syncEventDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s syncEventDo) Order(conds ...field.Expr) *syncEventDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s syncEventDo) Distinct(cols ...field.Expr) *syncEventDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s syncEventDo) Omit(cols ...field.Expr) *syncEventDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s syncEventDo) Join(table schema.Tabler, on ...field.Expr) *syncEventDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s syncEventDo) LeftJoin(table schema.Tabler, on ...field.Expr) *syncEventDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s syncEventDo) RightJoin(table schema.Tabler, on ...field.Expr) *syncEventDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s syncEventDo) Group(cols ...field.Expr) *syncEventDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s syncEventDo) Having(conds ...gen.Condition) *syncEventDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s syncEventDo) Limit(limit int) *syncEventDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s syncEventDo) Offset(offset int) *syncEventDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s syncEventDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *syncEventDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s syncEventDo) Unscoped() *syncEventDo {
	return s.withDO(s.DO.Unscoped())
}

func (s syncEventDo) Create(values ...*models.SyncEvent) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s syncEventDo) CreateInBatches(values []*models.SyncEvent, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s syncEventDo) Save(values ...*models.SyncEvent) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s syncEventDo) First() (*models.SyncEvent, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.SyncEvent), nil
	}
}

func (s syncEventDo) Take() (*models.SyncEvent, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.SyncEvent), nil
	}
}

func (s syncEventDo) Last() (*models.SyncEvent, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.SyncEvent), nil
	}
}

func (s syncEventDo) Find() ([]*models.SyncEvent, error) {
	result, err := s.DO.Find()
	return result.([]*models.SyncEvent), err
}

func (s syncEventDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.SyncEvent, err error) {
	buf := make([]*models.SyncEvent, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s syncEventDo) FindInBatches(result *[]*models.SyncEvent, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s syncEventDo) Attrs(attrs ...field.AssignExpr) *syncEventDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s syncEventDo) Assign(attrs ...field.AssignExpr) *syncEventDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s syncEventDo) Joins(fields ...field.RelationField) *syncEventDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s syncEventDo) Preload(fields ...field.RelationField) *syncEventDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s syncEventDo) FirstOrInit() (*models.SyncEvent, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.SyncEvent), nil
	}
}

func (s syncEventDo) FirstOrCreate() (*models.SyncEvent, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.SyncEvent), nil
	}
}

func (s syncEventDo) FindByPage(offset int, limit int) (result []*models.SyncEvent, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s syncEventDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s syncEventDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s syncEventDo) Delete(models ...*models.SyncEvent) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *syncEventDo) withDO(do gen.Dao) *syncEventDo {
	s.DO = *do.(*gen.DO)
	return s
}
